name: Collect Comments and Export to CSV

on:
  pull_request:
    types:
      - review
      - opened


  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  collect-comments:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Collect Comments and Export to CSV
        run: |
          # python .github/scripts/collect_comments.py ${{ github.event.client_payload.pull_request.number }}
          # python .github/scripts/collect_comments.py ${{ github.event.pull_request.number }}
          python .github/scripts/collect_comments.py 2
